import { NewsItem, Model } from './types'

export const subcategoryConfig: Record<string, { label: string; icon: string; color: string; description: string }> = {
  code: { label: 'Code', icon: '⌨️', color: '#22c55e', description: 'Modèles spécialisés en programmation' },
  vision: { label: 'Vision', icon: '👁️', color: '#8b5cf6', description: 'Compréhension d\'images et documents visuels' },
  agent: { label: 'Agent', icon: '🤖', color: '#f59e0b', description: 'IA autonome qui utilise des outils' },
  reasoning: { label: 'Raisonnement', icon: '🧠', color: '#ec4899', description: 'Raisonnement avancé et logique' },
  chat: { label: 'Conversation', icon: '💬', color: '#6366f1', description: 'Conversation et tâches générales' },
  audio: { label: 'Audio', icon: '🎤', color: '#06b6d4', description: 'Voix, transcription et son' },
  embedding: { label: 'Embedding', icon: '🔗', color: '#84cc16', description: 'Recherche sémantique et similarité' },
  specialized: { label: 'Spécialisé', icon: '🎯', color: '#f97316', description: 'Domaines spécifiques (médical, juridique...)' },
}

export const mockNews: NewsItem[] = [
  {
    id: 'n1',
    title: 'GPT-5 est disponible : performances en hausse de 40% sur le raisonnement',
    summary: 'OpenAI lance GPT-5 avec des améliorations majeures sur le raisonnement, le code et la compréhension multimodale. Arena ELO en hausse de 50 points.',
    source: 'OpenAI',
    category: 'release',
    published_at: '2026-05-01T18:30:00Z',
    url: 'https://openai.com/blog/gpt-5',
    tags: ['GPT-5', 'OpenAI', 'raisonnement', 'code'],
    is_breaking: true,
    hype_score: 95,
  },
  {
    id: 'n2',
    title: 'Claude Opus 5 bat tous les records sur HumanEval et GPQA',
    summary: 'Anthropic publie Claude Opus 5 avec un score HumanEval de 96.5% et GPQA de 78%. Le meilleur modèle pour le code et le raisonnement expert.',
    source: 'Anthropic',
    category: 'release',
    published_at: '2026-05-01T14:00:00Z',
    url: 'https://anthropic.com/blog/claude-opus-5',
    tags: ['Claude', 'Anthropic', 'code', 'raisonnement'],
    is_breaking: true,
    hype_score: 92,
  },
  {
    id: 'n3',
    title: 'Nouveau benchmark MLE-bench : évaluer les agents IA sur des tâches réelles',
    summary: 'Un benchmark révolutionnaire teste la capacité des agents IA à accomplir des tâches d\'ingénierie ML de bout en bout.',
    source: 'ArXiv',
    category: 'benchmark',
    published_at: '2026-05-01T10:00:00Z',
    url: 'https://arxiv.org/abs/2410.04126',
    tags: ['benchmark', 'agent', 'MLE-bench'],
    is_breaking: false,
    hype_score: 78,
  },
  {
    id: 'n4',
    title: 'Gemini 3 Pro : Google lance son modèle agent avec utilisation d\'outils',
    summary: 'Google présente Gemini 3 Pro avec des capacités agent avancées : navigation web, exécution de code, appels API autonomes.',
    source: 'Google',
    category: 'release',
    published_at: '2026-04-30T16:00:00Z',
    url: 'https://blog.google/ai/gemini-3-pro',
    tags: ['Gemini', 'Google', 'agent', 'outils'],
    is_breaking: false,
    hype_score: 85,
  },
  {
    id: 'n5',
    title: 'Llama 4 : Meta ouvre son modèle 400B avec des performances proches de GPT-5',
    summary: 'Meta libère Llama 4 en open-source avec 400B paramètres. Le premier modèle libre à dépasser 90% au MMLU.',
    source: 'Meta',
    category: 'release',
    published_at: '2026-04-30T12:00:00Z',
    url: 'https://ai.meta.com/blog/llama-4',
    tags: ['Llama', 'Meta', 'open-source', 'libre'],
    is_breaking: false,
    hype_score: 88,
  },
  {
    id: 'n6',
    title: 'Les modèles de code surpassent les développeurs juniors sur des tâches réelles',
    summary: 'Une étude montre que les modèles de code comme Claude Opus 5 et GPT-5 produisent du code fonctionnel plus rapidement que des développeurs juniors.',
    source: 'ArXiv',
    category: 'research',
    published_at: '2026-04-29T09:00:00Z',
    url: 'https://arxiv.org/abs/2410.02156',
    tags: ['code', 'recherche', 'productivité'],
    is_breaking: false,
    hype_score: 72,
  },
  {
    id: 'n7',
    title: 'Mistral Large 3 : le modèle européen rivalise avec les leaders américains',
    summary: 'Mistral AI lance Large 3 avec un ELO de 1298 et un prix 3x inférieur à GPT-5.',
    source: 'VentureBeat',
    category: 'industry',
    published_at: '2026-04-29T11:00:00Z',
    url: 'https://mistral.ai/blog/mistral-large-3',
    tags: ['Mistral', 'Europe', 'prix'],
    is_breaking: false,
    hype_score: 68,
  },
  {
    id: 'n8',
    title: 'DeepSeek-R1 démocratise le raisonnement avancé en open-source',
    summary: 'DeepSeek publie R1, un modèle de raisonnement open-source qui rivalise avec o3 sur les tâches mathématiques et logiques.',
    source: 'HuggingFace',
    category: 'release',
    published_at: '2026-04-28T07:00:00Z',
    url: 'https://huggingface.co/deepseek-ai/DeepSeek-R1',
    tags: ['DeepSeek', 'raisonnement', 'open-source'],
    is_breaking: false,
    hype_score: 82,
  },
  {
    id: 'n9',
    title: 'Les agents IA changent la donne : 5 frameworks comparés',
    summary: 'Comparatif des principaux frameworks d\'agents : LangGraph, CrewAI, AutoGen, OpenAI Agents SDK et Anthropic Computer Use.',
    source: 'MIT Tech Review',
    category: 'industry',
    published_at: '2026-04-28T13:00:00Z',
    url: 'https://technologyreview.com/ai-agents-frameworks',
    tags: ['agent', 'framework', 'comparatif'],
    is_breaking: false,
    hype_score: 65,
  },
  {
    id: 'n10',
    title: 'GPT-5 Vision : analyse d\'images médicales avec 94% de précision',
    summary: 'OpenAI annonce que GPT-5 Vision atteint 94% de précision sur l\'analyse de radiographies.',
    source: 'The Verge',
    category: 'research',
    published_at: '2026-04-27T15:00:00Z',
    url: 'https://theverge.com/2025/6/6/gpt5-vision-medical',
    tags: ['vision', 'médical', 'GPT-5'],
    is_breaking: false,
    hype_score: 75,
  },
  {
    id: 'n11',
    title: 'Sora 2 génère des vidéos de 2 minutes cohérentes',
    summary: 'OpenAI améliore Sora avec des vidéos plus longues et plus cohérentes.',
    source: 'OpenAI',
    category: 'release',
    published_at: '2026-04-27T10:00:00Z',
    url: 'https://openai.com/blog/sora-2',
    tags: ['vidéo', 'Sora', 'génératif'],
    is_breaking: false,
    hype_score: 70,
  },
  {
    id: 'n12',
    title: 'Le RAG est mort ? Les modèles à contexte 1M+ rendent le retrieval obsolète',
    summary: 'Avec des fenêtres de contexte dépassant le million de tokens, certains se demandent si le RAG est toujours nécessaire.',
    source: 'VentureBeat',
    category: 'research',
    published_at: '2026-04-26T08:00:00Z',
    url: 'https://venturebeat.com/rag-dead-long-context',
    tags: ['RAG', 'contexte', 'débat'],
    is_breaking: false,
    hype_score: 60,
  },
  {
    id: 'n13',
    title: 'Whisper v4 : transcription vocale quasi-parfaite en temps réel',
    summary: 'OpenAI lance Whisper v4 avec un taux d\'erreur de 1.2% sur le français.',
    source: 'OpenAI',
    category: 'release',
    published_at: '2026-04-26T09:00:00Z',
    url: 'https://openai.com/blog/whisper-v4',
    tags: ['audio', 'transcription', 'Whisper'],
    is_breaking: false,
    hype_score: 55,
  },
  {
    id: 'n14',
    title: 'Comment choisir son modèle IA en 2025 : guide complet',
    summary: 'Guide pour débutants et pros : quel modèle pour quelle tâche ? Code, vision, agents, chat — on fait le point.',
    source: 'HuggingFace',
    category: 'industry',
    published_at: '2026-04-25T12:00:00Z',
    url: 'https://huggingface.co/blog/choose-your-model-2025',
    tags: ['guide', 'choix', 'débutant'],
    is_breaking: false,
    hype_score: 58,
  },
  {
    id: 'n15',
    title: 'Grok 3 d\'xAI : un agent Twitter intégré qui exécute des actions',
    summary: 'xAI lance Grok 3 avec des capacités agent sur X/Twitter.',
    source: 'xAI',
    category: 'release',
    published_at: '2026-04-25T14:00:00Z',
    url: 'https://x.ai/blog/grok-3',
    tags: ['Grok', 'xAI', 'agent', 'Twitter'],
    is_breaking: false,
    hype_score: 62,
  },
  {
    id: 'n16',
    title: 'Qwen 3 d\'Alibaba domine le benchmark multilingue avec 95% en français',
    summary: 'Le modèle chinois Qwen 3 surprend avec d\'excellentes performances en français et 30+ langues.',
    source: 'Alibaba',
    category: 'release',
    published_at: '2026-04-24T08:00:00Z',
    url: 'https://qwenlm.github.io/blog/qwen3',
    tags: ['Qwen', 'multilingue', 'français'],
    is_breaking: false,
    hype_score: 64,
  },
  {
    id: 'n17',
    title: 'Les LLM open-source dépassent les propriétaires pour la première fois',
    summary: 'Llama 4 et DeepSeek-R1 atteignent des scores Arena ELO supérieurs à certains modèles propriétaires.',
    source: 'The Verge',
    category: 'industry',
    published_at: '2026-04-24T10:00:00Z',
    url: 'https://theverge.com/open-source-beats-proprietary',
    tags: ['open-source', 'tournant', 'libre'],
    is_breaking: false,
    hype_score: 76,
  },
  {
    id: 'n18',
    title: 'Les modèles de raisonnement chain-of-thought sont-ils vraiment meilleurs ?',
    summary: 'Des chercheurs du MIT remettent en question l\'efficacité du chain-of-thought pour les tâches pratiques.',
    source: 'ArXiv',
    category: 'research',
    published_at: '2026-04-23T07:00:00Z',
    url: 'https://arxiv.org/abs/2410.01123',
    tags: ['raisonnement', 'CoT', 'recherche'],
    is_breaking: false,
    hype_score: 52,
  },
  {
    id: 'n19',
    title: 'Anthropic publie un framework de sécurité pour les agents IA',
    summary: 'Anthropic propose des guidelines pour construire des agents IA sûrs : sandboxing, permissions, supervision humaine.',
    source: 'Anthropic',
    category: 'industry',
    published_at: '2026-04-23T09:00:00Z',
    url: 'https://anthropic.com/blog/agent-safety',
    tags: ['sécurité', 'agent', 'guidelines'],
    is_breaking: false,
    hype_score: 58,
  },
  {
    id: 'n20',
    title: 'Cohere Rerank 4 : la recherche sémantique enfin précise',
    summary: 'Cohere améliore son modèle de reranking avec 15% de précision en plus. Idéal pour les pipelines RAG.',
    source: 'Cohere',
    category: 'release',
    published_at: '2026-04-22T11:00:00Z',
    url: 'https://cohere.com/blog/rerank-4',
    tags: ['embedding', 'RAG', 'recherche'],
    is_breaking: false,
    hype_score: 48,
  },
  {
    id: 'n21',
    title: 'Microsoft Phi-4 : petit modèle, grandes performances',
    summary: 'Phi-4 (3.8B paramètres) atteint 85% au MMLU. La taille n\'est pas tout — l\'entraînement compte.',
    source: 'Microsoft',
    category: 'release',
    published_at: '2026-04-22T08:00:00Z',
    url: 'https://microsoft.com/phi-4',
    tags: ['Phi', 'petit modèle', 'efficace'],
    is_breaking: false,
    hype_score: 55,
  },
  {
    id: 'n22',
    title: 'OpenAI o3 : le modèle de raisonnement qui résout les problèmes de niveau PhD',
    summary: 'o3 atteint 87% sur GPQA et résout des problèmes de mathématiques de compétition.',
    source: 'OpenAI',
    category: 'release',
    published_at: '2026-04-21T10:00:00Z',
    url: 'https://openai.com/blog/o3',
    tags: ['o3', 'raisonnement', 'PhD'],
    is_breaking: false,
    hype_score: 80,
  },
  {
    id: 'n23',
    title: '73% des Fortune 500 utilisent des LLMs en production',
    summary: 'Une étude McKinsey montre l\'adoption massive des LLMs en entreprise en 2025.',
    source: 'MIT Tech Review',
    category: 'industry',
    published_at: '2026-04-21T12:00:00Z',
    url: 'https://technologyreview.com/fortune-500-llm',
    tags: ['entreprise', 'production', 'adoption'],
    is_breaking: false,
    hype_score: 50,
  },
  {
    id: 'n24',
    title: 'Claude Sonnet 4 : le meilleur rapport qualité-prix du marché',
    summary: 'Anthropic lance Sonnet 4 à $1/$5 par 1M tokens avec des performances proches d\'Opus 5.',
    source: 'Anthropic',
    category: 'release',
    published_at: '2026-04-20T09:00:00Z',
    url: 'https://anthropic.com/blog/claude-sonnet-4',
    tags: ['Claude', 'Sonnet', 'prix', 'économique'],
    is_breaking: false,
    hype_score: 72,
  },
  {
    id: 'n25',
    title: 'Stable Diffusion 4 : la génération d\'images rattrape DALL-E 3',
    summary: 'Stability AI lance SD4 en open-source avec une qualité visuelle comparable à DALL-E 3.',
    source: 'HuggingFace',
    category: 'release',
    published_at: '2026-04-20T07:00:00Z',
    url: 'https://stability.ai/blog/sd4',
    tags: ['image', 'Stable Diffusion', 'open-source'],
    is_breaking: false,
    hype_score: 63,
  },
]

export const mockModels: Model[] = [
  {
    id: 'gpt5',
    name: 'GPT-5',
    provider: 'OpenAI',
    type: 'proprietary',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1342, mmlu: 93.5, humaneval: 95.2, math: 82.1, gpqa: 72.3, speed_tps: 85, price_input: 5, price_output: 15 },
    context_window: 256000,
    parameters: '~2T (MoE)',
    release_date: '2026-05-01',
    changelog_url: 'https://openai.com/blog/gpt-5',
    is_new: true,
    rank_delta_7d: 2,
    description: 'Le modèle phare d\'OpenAI. Excellent en conversation, raisonnement et code. Fenêtre de contexte massive de 256k.',
    best_for: ['Conversation avancée', 'Raisonnement', 'Code', 'Analyse de documents longs'],
    api_available: true,
  },
  {
    id: 'claude-opus-5',
    name: 'Claude Opus 5',
    provider: 'Anthropic',
    type: 'proprietary',
    subcategory: 'code',
    subcategory_label: 'Code',
    scores: { arena_elo: 1319, mmlu: 92.8, humaneval: 96.5, math: 80.5, gpqa: 78.1, speed_tps: 65, price_input: 15, price_output: 75 },
    context_window: 200000,
    parameters: '~1.5T',
    release_date: '2026-05-01',
    changelog_url: 'https://anthropic.com/blog/claude-opus-5',
    is_new: true,
    rank_delta_7d: 1,
    description: 'Le meilleur modèle pour le code et le raisonnement expert. Score HumanEval record de 96.5%.',
    best_for: ['Code', 'Raisonnement expert', 'GPQA', 'Tâches complexes'],
    api_available: true,
  },
  {
    id: 'gemini-3-pro',
    name: 'Gemini 3 Pro',
    provider: 'Google',
    type: 'proprietary',
    subcategory: 'agent',
    subcategory_label: 'Agent',
    scores: { arena_elo: 1298, mmlu: 91.2, humaneval: 90.8, math: 78.3, gpqa: 70.5, speed_tps: 110, price_input: 1.25, price_output: 5 },
    context_window: 2000000,
    parameters: '~1.8T (MoE)',
    release_date: '2026-04-30',
    changelog_url: 'https://blog.google/ai/gemini-3-pro',
    is_new: true,
    rank_delta_7d: 3,
    description: 'Le modèle agent de Google avec 2M tokens de contexte et utilisation native d\'outils.',
    best_for: ['Agents autonomes', 'Contexte ultra-long', 'Utilisation d\'outils', 'Multimodal'],
    api_available: true,
  },
  {
    id: 'llama-4-maverick',
    name: 'Llama 4 Maverick',
    provider: 'Meta',
    type: 'open',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1285, mmlu: 90.1, humaneval: 88.5, math: 75.2, gpqa: 65.8, speed_tps: 95, price_input: null, price_output: null },
    context_window: 128000,
    parameters: '400B (MoE)',
    release_date: '2026-04-30',
    changelog_url: 'https://ai.meta.com/blog/llama-4',
    is_new: true,
    rank_delta_7d: 5,
    description: 'Le meilleur modèle open-source de Meta. 400B paramètres avec MoE.',
    best_for: ['Auto-hébergement', 'Fine-tuning', 'Conversation', 'Recherche'],
    api_available: false,
  },
  {
    id: 'o3',
    name: 'o3',
    provider: 'OpenAI',
    type: 'proprietary',
    subcategory: 'reasoning',
    subcategory_label: 'Raisonnement',
    scores: { arena_elo: 1275, mmlu: 88.5, humaneval: 92.1, math: 96.3, gpqa: 87.4, speed_tps: 25, price_input: 10, price_output: 40 },
    context_window: 200000,
    parameters: 'Non divulgué',
    release_date: '2026-04-21',
    changelog_url: 'https://openai.com/blog/o3',
    is_new: false,
    rank_delta_7d: -1,
    description: 'Le modèle de raisonnement d\'OpenAI. Record sur MATH (96.3%) et GPQA (87.4%).',
    best_for: ['Mathématiques', 'Raisonnement logique', 'Problèmes de niveau PhD', 'Science'],
    api_available: true,
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek-R1',
    provider: 'DeepSeek',
    type: 'open',
    subcategory: 'reasoning',
    subcategory_label: 'Raisonnement',
    scores: { arena_elo: 1265, mmlu: 87.2, humaneval: 89.5, math: 92.8, gpqa: 75.2, speed_tps: 40, price_input: null, price_output: null },
    context_window: 128000,
    parameters: '671B (MoE)',
    release_date: '2026-04-28',
    changelog_url: 'https://huggingface.co/deepseek-ai/DeepSeek-R1',
    is_new: false,
    rank_delta_7d: 2,
    description: 'Le modèle de raisonnement open-source le plus puissant. Rivalise avec o3.',
    best_for: ['Raisonnement open-source', 'Mathématiques', 'Auto-hébergement', 'Recherche'],
    api_available: false,
  },
  {
    id: 'claude-sonnet-4',
    name: 'Claude Sonnet 4',
    provider: 'Anthropic',
    type: 'proprietary',
    subcategory: 'code',
    subcategory_label: 'Code',
    scores: { arena_elo: 1250, mmlu: 88.9, humaneval: 93.8, math: 76.5, gpqa: 68.2, speed_tps: 120, price_input: 1, price_output: 5 },
    context_window: 200000,
    parameters: '~200B',
    release_date: '2026-04-20',
    changelog_url: 'https://anthropic.com/blog/claude-sonnet-4',
    is_new: false,
    rank_delta_7d: 0,
    description: 'Le meilleur rapport qualité-prix. 2x plus rapide qu\'Opus pour un prix 15x inférieur.',
    best_for: ['Code en production', 'Rapport qualité-prix', 'Tâches quotidiennes', 'API économique'],
    api_available: true,
  },
  {
    id: 'mistral-large-3',
    name: 'Mistral Large 3',
    provider: 'Mistral',
    type: 'proprietary',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1298, mmlu: 89.5, humaneval: 85.2, math: 72.1, gpqa: 62.5, speed_tps: 100, price_input: 2, price_output: 6 },
    context_window: 128000,
    parameters: '~120B',
    release_date: '2026-04-29',
    changelog_url: 'https://mistral.ai/blog/mistral-large-3',
    is_new: false,
    rank_delta_7d: 1,
    description: 'Le modèle européen de référence. Conforme RGPD, disponible sur les clouds européens.',
    best_for: ['Conformité RGPD', 'Multilingue', 'Cloud européen', 'Conversation'],
    api_available: true,
  },
  {
    id: 'grok-3',
    name: 'Grok 3',
    provider: 'xAI',
    type: 'proprietary',
    subcategory: 'agent',
    subcategory_label: 'Agent',
    scores: { arena_elo: 1240, mmlu: 86.5, humaneval: 82.3, math: 70.2, gpqa: 58.9, speed_tps: 90, price_input: 3, price_output: 10 },
    context_window: 128000,
    parameters: '~300B',
    release_date: '2026-04-25',
    changelog_url: 'https://x.ai/blog/grok-3',
    is_new: false,
    rank_delta_7d: -2,
    description: 'L\'agent IA intégré à X/Twitter. Recherche en temps réel et actions sur la plateforme.',
    best_for: ['Recherche temps réel', 'Twitter/X', 'Tendances', 'Actualités'],
    api_available: true,
  },
  {
    id: 'qwen-3',
    name: 'Qwen 3',
    provider: 'Alibaba',
    type: 'open',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1232, mmlu: 88.2, humaneval: 84.5, math: 74.8, gpqa: 60.1, speed_tps: 88, price_input: null, price_output: null },
    context_window: 128000,
    parameters: '110B',
    release_date: '2026-04-24',
    changelog_url: 'https://qwenlm.github.io/blog/qwen3',
    is_new: false,
    rank_delta_7d: 1,
    description: 'Le modèle multilingue par excellence. 95% de précision en français.',
    best_for: ['Multilingue', 'Français', 'Auto-hébergement', 'Asie-Pacifique'],
    api_available: false,
  },
  {
    id: 'gpt5-vision',
    name: 'GPT-5 Vision',
    provider: 'OpenAI',
    type: 'proprietary',
    subcategory: 'vision',
    subcategory_label: 'Vision',
    scores: { arena_elo: 1260, mmlu: 91.0, humaneval: null, math: null, gpqa: null, speed_tps: 60, price_input: 8, price_output: 24 },
    context_window: 256000,
    parameters: '~2T (MoE)',
    release_date: '2026-05-01',
    changelog_url: 'https://openai.com/blog/gpt-5-vision',
    is_new: true,
    rank_delta_7d: 4,
    description: 'Version multimodale de GPT-5. Analyse d\'images, documents, graphiques. 94% sur radiographies.',
    best_for: ['Analyse d\'images', 'Documents visuels', 'Médical', 'OCR avancé'],
    api_available: true,
  },
  {
    id: 'llama-4-scout',
    name: 'Llama 4 Scout',
    provider: 'Meta',
    type: 'open',
    subcategory: 'vision',
    subcategory_label: 'Vision',
    scores: { arena_elo: 1210, mmlu: 85.2, humaneval: 80.1, math: 68.5, gpqa: 55.2, speed_tps: 130, price_input: null, price_output: null },
    context_window: 256000,
    parameters: '109B (MoE)',
    release_date: '2026-04-30',
    changelog_url: 'https://ai.meta.com/blog/llama-4-scout',
    is_new: true,
    rank_delta_7d: 3,
    description: 'Version vision de Llama 4 en open-source. Rapide et efficace pour l\'analyse d\'images.',
    best_for: ['Vision open-source', 'Analyse d\'images', 'Rapidité', 'Auto-hébergement'],
    api_available: false,
  },
  {
    id: 'phi-4',
    name: 'Phi-4',
    provider: 'Microsoft',
    type: 'open',
    subcategory: 'specialized',
    subcategory_label: 'Spécialisé',
    scores: { arena_elo: 1180, mmlu: 85.0, humaneval: 78.5, math: 72.3, gpqa: 55.8, speed_tps: 200, price_input: null, price_output: null },
    context_window: 32000,
    parameters: '3.8B',
    release_date: '2026-04-22',
    changelog_url: 'https://microsoft.com/phi-4',
    is_new: false,
    rank_delta_7d: 0,
    description: 'Petit mais puissant. 3.8B paramètres avec 85% au MMLU. Parfait pour les appareils limités.',
    best_for: ['Edge/mobile', 'Petit modèle', 'Rapidité extrême', 'Fine-tuning facile'],
    api_available: false,
  },
  {
    id: 'whisper-v4',
    name: 'Whisper v4',
    provider: 'OpenAI',
    type: 'open',
    subcategory: 'audio',
    subcategory_label: 'Audio',
    scores: { arena_elo: null, mmlu: null, humaneval: null, math: null, gpqa: null, speed_tps: null, price_input: 0.006, price_output: 0.006 },
    context_window: 0,
    parameters: '1.5B',
    release_date: '2026-04-26',
    changelog_url: 'https://openai.com/blog/whisper-v4',
    is_new: false,
    rank_delta_7d: 0,
    description: 'Le meilleur modèle de transcription vocale. 1.2% de taux d\'erreur en français.',
    best_for: ['Transcription', 'Sous-titres', 'Français', 'Temps réel'],
    api_available: true,
  },
  {
    id: 'cohere-rerank-4',
    name: 'Rerank 4',
    provider: 'Cohere',
    type: 'proprietary',
    subcategory: 'embedding',
    subcategory_label: 'Embedding',
    scores: { arena_elo: null, mmlu: null, humaneval: null, math: null, gpqa: null, speed_tps: null, price_input: 0.1, price_output: 0.1 },
    context_window: 8000,
    parameters: '~400M',
    release_date: '2026-04-22',
    changelog_url: 'https://cohere.com/blog/rerank-4',
    is_new: false,
    rank_delta_7d: 0,
    description: 'Le meilleur modèle de reranking pour les pipelines RAG. 15% de précision en plus.',
    best_for: ['RAG', 'Recherche sémantique', 'Reranking', 'Enterprise search'],
    api_available: true,
  },
]
