import { NewsItem, Model } from './types'

export const subcategoryConfig: Record<string, { label: string; icon: string; color: string; description: string }> = {
  code: { label: 'Code', icon: '⌨️', color: '#22c55e', description: 'Modèles spécialisés en programmation' },
  vision: { label: 'Vision', icon: '👁️', color: '#8b5cf6', description: 'Compréhension d\'images et documents visuels' },
  agent: { label: 'Agent', icon: '🤖', color: '#f59e0b', description: 'IA autonome qui utilise des outils' },
  reasoning: { label: 'Raisonnement', icon: '🧠', color: '#ec4899', description: 'Raisonnement avancé et logique' },
  chat: { label: 'Conversation', icon: '💬', color: '#6366f1', description: 'Conversation et tâches générales' },
  audio: { label: 'Audio', icon: '🎤', color: '#06b6d4', description: 'Voix, transcription et son' },
  embedding: { label: 'Embedding', icon: '🔗', color: '#84cc16', description: 'Recherche sémantique et similarité' },
  specialized: { label: 'Spécialisé', icon: '🎯', color: '#f97316', description: 'Domaines spécifiques (médical, juridique...)' },
}

// Données de fallback plausibles (mai 2026) — utilisées uniquement si les APIs temps réel échouent
export const mockNews: NewsItem[] = [
  {
    id: 'n1',
    title: 'GPT-5 officiel : OpenAI franchit un nouveau cap sur le raisonnement multimodal',
    summary: 'OpenAI dévoile GPT-5 avec des capacités de raisonnement en chaîne sur texte, image, audio et vidéo. ELO Arena estimé à 1382.',
    source: 'OpenAI',
    category: 'release',
    published_at: '2026-04-15T10:00:00Z',
    url: 'https://openai.com/news/gpt-5',
    tags: ['GPT-5', 'OpenAI', 'multimodal', 'release'],
    is_breaking: true,
    hype_score: 97,
  },
  {
    id: 'n2',
    title: 'Claude 5 : Anthropic repousse les limites du contexte et du raisonnement',
    summary: 'Anthropic présente Claude 5 avec 500K tokens de contexte natif et des performances record sur GPQA et SWE-bench.',
    source: 'Anthropic',
    category: 'release',
    published_at: '2026-04-10T14:00:00Z',
    url: 'https://anthropic.com/news/claude-5',
    tags: ['Claude', 'Anthropic', 'raisonnement', 'contexte'],
    is_breaking: true,
    hype_score: 95,
  },
  {
    id: 'n3',
    title: 'Gemini 3 Pro : Google affirme sa suprématie sur les benchmarks STEM',
    summary: 'Google lance Gemini 3 Pro avec un score MATH de 98.1% et une fenêtre de contexte de 2M tokens, ciblant les chercheurs.',
    source: 'Google',
    category: 'release',
    published_at: '2026-04-05T09:00:00Z',
    url: 'https://blog.google/technology/ai/gemini-3-pro/',
    tags: ['Gemini', 'Google', 'STEM', 'benchmark'],
    is_breaking: true,
    hype_score: 92,
  },
  {
    id: 'n4',
    title: 'Llama 5 : Meta open-source un modèle à 1T paramètres (MoE)',
    summary: 'Meta publie Llama 5 en open-weight avec une architecture MoE de 1T paramètres et 64B actifs, battant GPT-4.5 sur Arena.',
    source: 'Meta',
    category: 'release',
    published_at: '2026-03-28T12:00:00Z',
    url: 'https://ai.meta.com/blog/llama-5/',
    tags: ['Llama', 'Meta', 'open-source', 'MoE'],
    is_breaking: true,
    hype_score: 91,
  },
  {
    id: 'n5',
    title: 'OpenAI baisse les prix de GPT-5 mini de 60% face à la concurrence open-source',
    summary: 'Sous la pression de Llama 5 et DeepSeek-V4, OpenAI réduit drastiquement les tarifs API de sa gamme économique.',
    source: 'OpenAI',
    category: 'pricing',
    published_at: '2026-03-22T15:00:00Z',
    url: 'https://openai.com/api/pricing/',
    tags: ['GPT-5', 'OpenAI', 'prix', 'API'],
    is_breaking: false,
    hype_score: 84,
  },
  {
    id: 'n6',
    title: 'DeepSeek-V4 : le modèle chinois dépasse Claude 5 sur les benchmarks de code',
    summary: 'DeepSeek-V4 atteint 96% sur HumanEval et coûte 20x moins cher que les modèles frontier américains.',
    source: 'DeepSeek',
    category: 'benchmark',
    published_at: '2026-03-18T10:00:00Z',
    url: 'https://deepseek.ai/blog/deepseek-v4',
    tags: ['DeepSeek', 'code', 'prix', 'benchmark'],
    is_breaking: true,
    hype_score: 90,
  },
  {
    id: 'n7',
    title: 'Mistral Large 3 : le champion européen atteint le top 5 mondial',
    summary: 'Mistral AI lance Large 3 avec des performances égales à GPT-5 mini et une conformité RGPD native pour l\'Europe.',
    source: 'Mistral',
    category: 'release',
    published_at: '2026-03-15T11:00:00Z',
    url: 'https://mistral.ai/news/mistral-large-3',
    tags: ['Mistral', 'Europe', 'RGPD', 'release'],
    is_breaking: false,
    hype_score: 82,
  },
  {
    id: 'n8',
    title: 'o5 : OpenAI révolutionne le raisonnement scientifique de niveau doctorat',
    summary: 'Le nouveau modèle de raisonnement o5 atteint 94% sur GPQA Diamond, surpassant les experts humains en physique et chimie.',
    source: 'OpenAI',
    category: 'release',
    published_at: '2026-03-10T14:00:00Z',
    url: 'https://openai.com/news/o5',
    tags: ['o5', 'OpenAI', 'raisonnement', 'science'],
    is_breaking: true,
    hype_score: 93,
  },
  {
    id: 'n9',
    title: 'Qwen 3 : Alibaba dévoile un modèle multilingue de 72B dominant le français',
    summary: 'Qwen 3 établit un nouveau standard pour les LLM multilingues avec des performances record sur les benchmarks francophones.',
    source: 'Alibaba',
    category: 'release',
    published_at: '2026-03-05T09:00:00Z',
    url: 'https://qwenlm.github.io/blog/qwen3/',
    tags: ['Qwen', 'Alibaba', 'multilingue', 'français'],
    is_breaking: false,
    hype_score: 78,
  },
  {
    id: 'n10',
    title: 'xAI lance Grok 4 avec un cluster d\'entraînement de 300K GPUs',
    summary: 'Elon Musk annonce Grok 4, entraîné sur le plus grand cluster de compute dédié à l\'IA, avec un focus sur le raisonnement mathématique.',
    source: 'xAI',
    category: 'release',
    published_at: '2026-03-01T11:00:00Z',
    url: 'https://x.ai/blog/grok-4',
    tags: ['Grok', 'xAI', 'compute', 'mathématiques'],
    is_breaking: true,
    hype_score: 88,
  },
  {
    id: 'n11',
    title: 'Les agents IA autonomes atteignent 40% de résolution sur SWE-bench Verified',
    summary: 'Une étude montre que les agents basés sur GPT-5 et Claude 5 résolvent désormais 40% des tickets GitHub réels sans supervision.',
    source: 'ArXiv',
    category: 'research',
    published_at: '2026-02-25T08:00:00Z',
    url: 'https://arxiv.org/abs/2602.11500',
    tags: ['agents', 'SWE-bench', 'autonomie', 'recherche'],
    is_breaking: false,
    hype_score: 85,
  },
  {
    id: 'n12',
    title: 'Nouvelle régulation UE : les LLM doivent afficher leur empreinte carbone',
    summary: 'La Commission européenne impose aux fournisseurs de LLM de divulguer l\'empreinte carbone de l\'entraînement et de l\'inférence.',
    source: 'UE',
    category: 'industry',
    published_at: '2026-02-20T13:00:00Z',
    url: 'https://digital-strategy.ec.europa.eu/en/policies/ai-act',
    tags: ['régulation', 'UE', 'carbone', 'IA Act'],
    is_breaking: false,
    hype_score: 76,
  },
  {
    id: 'n13',
    title: 'Apple Intelligence 2 : Siri devient un véritable assistant contextuel',
    summary: 'Apple déploie Intelligence 2 avec un modèle on-device de 7B et un backend GPT-5 mini, transformant l\'expérience iOS.',
    source: 'Apple',
    category: 'release',
    published_at: '2026-02-15T09:00:00Z',
    url: 'https://www.apple.com/newsroom/2026/02/apple-intelligence-2/',
    tags: ['Apple', 'on-device', 'Siri', 'mobile'],
    is_breaking: false,
    hype_score: 80,
  },
  {
    id: 'n14',
    title: 'Le marché des APIs IA atteint 28 milliards de dollars trimestriels',
    summary: 'Selon une analyse sectorielle, les revenus API des LLM ont dépassé 28Md$ au T1 2026, portés par l\'adoption des agents autonomes.',
    source: 'Industry',
    category: 'industry',
    published_at: '2026-02-10T11:00:00Z',
    url: 'https://www.bloomberg.com/news/articles/2026-02-10/ai-api-market',
    tags: ['marché', 'API', 'revenus', 'agents'],
    is_breaking: false,
    hype_score: 72,
  },
  {
    id: 'n15',
    title: 'Claude 5 bat le record mondial sur le benchmark de programmation SWE-bench',
    summary: 'Avec 52% de résolution sur SWE-bench Verified, Claude 5 établit un nouveau record pour un modèle généraliste.',
    source: 'Anthropic',
    category: 'benchmark',
    published_at: '2026-02-05T10:00:00Z',
    url: 'https://anthropic.com/research/claude-5-swe-bench',
    tags: ['Claude', 'SWE-bench', 'code', 'record'],
    is_breaking: false,
    hype_score: 83,
  },
]

// Modèles de fallback plausibles (mai 2026) — utilisés si les APIs temps réel échouent
export const mockModels: Model[] = [
  {
    id: 'gpt-5',
    name: 'GPT-5',
    provider: 'OpenAI',
    type: 'proprietary',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1385, mmlu: 93.2, humaneval: 94.1, math: 89.5, gpqa: 81.2, speed_tps: 120, price_input: 5.00, price_output: 20.00 },
    context_window: 256000,
    parameters: 'Non divulgué',
    release_date: '2026-04-15',
    changelog_url: 'https://openai.com/news/gpt-5',
    is_new: true,
    rank_delta_7d: 5,
    description: 'Modèle phare d\'OpenAI. Raisonnement multimodal natif sur texte, image, audio et vidéo. Leader sur Arena.',
    best_for: ['Conversation générale', 'Multimodal', 'Raisonnement complexe', 'Assistant virtuel'],
    api_available: true,
  },
  {
    id: 'claude-5',
    name: 'Claude 5',
    provider: 'Anthropic',
    type: 'proprietary',
    subcategory: 'reasoning',
    subcategory_label: 'Raisonnement',
    scores: { arena_elo: 1378, mmlu: 92.8, humaneval: 95.5, math: 87.3, gpqa: 79.8, speed_tps: 58, price_input: 6.00, price_output: 30.00 },
    context_window: 500000,
    parameters: 'Non divulgué',
    release_date: '2026-04-10',
    changelog_url: 'https://anthropic.com/news/claude-5',
    is_new: true,
    rank_delta_7d: 4,
    description: 'Contexte de 500K tokens natif. Record sur SWE-bench et HumanEval. Le meilleur pour le code et l\'analyse longue.',
    best_for: ['Code', 'Développement', 'Analyse longue', 'Raisonnement expert'],
    api_available: true,
  },
  {
    id: 'gemini-3-pro',
    name: 'Gemini 3 Pro',
    provider: 'Google',
    type: 'proprietary',
    subcategory: 'agent',
    subcategory_label: 'Agent',
    scores: { arena_elo: 1365, mmlu: 92.1, humaneval: 93.2, math: 90.1, gpqa: 78.5, speed_tps: 72, price_input: 2.50, price_output: 12.00 },
    context_window: 2000000,
    parameters: 'Non divulgué',
    release_date: '2026-04-05',
    changelog_url: 'https://blog.google/technology/ai/gemini-3-pro/',
    is_new: true,
    rank_delta_7d: 3,
    description: 'Contexte massif de 2M tokens et raisonnement STEM record (MATH 98.1%). Concurrent direct de GPT-5 et Claude 5.',
    best_for: ['Contexte ultra-long', 'STEM', 'Agents autonomes', 'Multimodal'],
    api_available: true,
  },
  {
    id: 'o5',
    name: 'o5',
    provider: 'OpenAI',
    type: 'proprietary',
    subcategory: 'reasoning',
    subcategory_label: 'Raisonnement',
    scores: { arena_elo: 1360, mmlu: 91.5, humaneval: 94.8, math: 96.2, gpqa: 94.0, speed_tps: 26, price_input: 15.00, price_output: 45.00 },
    context_window: 256000,
    parameters: 'Non divulgué',
    release_date: '2026-03-10',
    changelog_url: 'https://openai.com/news/o5',
    is_new: true,
    rank_delta_7d: 2,
    description: 'Raisonnement de niveau doctorat. 94% sur GPQA Diamond, surpassant les experts humains. Prix élevé mais inégalé en science.',
    best_for: ['Raisonnement', 'Mathématiques', 'Science', 'PhD-level'],
    api_available: true,
  },
  {
    id: 'deepseek-v4',
    name: 'DeepSeek-V4',
    provider: 'DeepSeek',
    type: 'open',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1345, mmlu: 90.5, humaneval: 96.0, math: 88.4, gpqa: 72.1, speed_tps: 52, price_input: 0.08, price_output: 1.20 },
    context_window: 256000,
    parameters: '1T (MoE)',
    release_date: '2026-03-18',
    changelog_url: 'https://deepseek.ai/blog/deepseek-v4',
    is_new: true,
    rank_delta_7d: 6,
    description: 'Open-source chinois à prix cassé. 96% HumanEval, 20x moins cher que les frontier US. Architecture MoE 1T paramètres.',
    best_for: ['Économique', 'Open-source', 'Code', 'API bon marché'],
    api_available: true,
  },
  {
    id: 'llama-5',
    name: 'Llama 5',
    provider: 'Meta',
    type: 'open',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1330, mmlu: 89.2, humaneval: 91.5, math: 82.3, gpqa: 70.5, speed_tps: 48, price_input: null, price_output: null },
    context_window: 512000,
    parameters: '1T total / 64B actifs (MoE)',
    release_date: '2026-03-28',
    changelog_url: 'https://ai.meta.com/blog/llama-5/',
    is_new: true,
    rank_delta_7d: 4,
    description: 'Open-weight MoE 1T/64B actifs. Contexte 512K. Première génération Llama à battre GPT-4.5 sur Arena. Auto-hébergement possible.',
    best_for: ['Auto-hébergement', 'Open-source', 'Contexte long', 'Recherche'],
    api_available: false,
  },
  {
    id: 'mistral-large-3',
    name: 'Mistral Large 3',
    provider: 'Mistral',
    type: 'proprietary',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1325, mmlu: 89.0, humaneval: 92.1, math: 80.8, gpqa: 69.2, speed_tps: 85, price_input: 1.50, price_output: 6.00 },
    context_window: 256000,
    parameters: 'Non divulgué',
    release_date: '2026-03-15',
    changelog_url: 'https://mistral.ai/news/mistral-large-3',
    is_new: true,
    rank_delta_7d: 3,
    description: 'Champion européen dans le top 5 mondial. Conformité RGPD native, excellent en français et code.',
    best_for: ['RGPD', 'Europe', 'Français', 'Code'],
    api_available: true,
  },
  {
    id: 'grok-4',
    name: 'Grok 4',
    provider: 'xAI',
    type: 'proprietary',
    subcategory: 'reasoning',
    subcategory_label: 'Raisonnement',
    scores: { arena_elo: 1318, mmlu: 89.5, humaneval: 90.8, math: 94.1, gpqa: 76.3, speed_tps: 55, price_input: 4.00, price_output: 18.00 },
    context_window: 256000,
    parameters: 'Non divulgué',
    release_date: '2026-03-01',
    changelog_url: 'https://x.ai/blog/grok-4',
    is_new: true,
    rank_delta_7d: 2,
    description: 'Entraîné sur le cluster Colossus de 300K GPUs. Excellents résultats MATH et accès natif aux données X/Twitter.',
    best_for: ['Raisonnement', 'Mathématiques', 'Actualités', 'Science'],
    api_available: true,
  },
  {
    id: 'qwen-3',
    name: 'Qwen 3',
    provider: 'Alibaba',
    type: 'open',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1305, mmlu: 88.1, humaneval: 89.5, math: 79.2, gpqa: 67.8, speed_tps: 68, price_input: 0.30, price_output: 0.80 },
    context_window: 256000,
    parameters: '72B',
    release_date: '2026-03-05',
    changelog_url: 'https://qwenlm.github.io/blog/qwen3/',
    is_new: true,
    rank_delta_7d: 3,
    description: 'Nouveau standard multilingue open-source. Dominant sur les benchmarks francophones et asiatiques.',
    best_for: ['Multilingue', 'Français', 'Open-source', 'Économique'],
    api_available: true,
  },
  {
    id: 'gemini-3-flash',
    name: 'Gemini 3 Flash',
    provider: 'Google',
    type: 'proprietary',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1290, mmlu: 86.5, humaneval: 87.2, math: 75.4, gpqa: 64.1, speed_tps: 190, price_input: 0.20, price_output: 0.80 },
    context_window: 1000000,
    parameters: 'Non divulgué',
    release_date: '2026-04-05',
    changelog_url: 'https://blog.google/technology/ai/gemini-3-flash/',
    is_new: true,
    rank_delta_7d: 1,
    description: 'Version rapide et économique de Gemini 3. Performances proches de Pro à prix cassé. Contexte 1M tokens.',
    best_for: ['Rapide', 'Économique', 'Contexte long', 'Chatbots'],
    api_available: true,
  },
  {
    id: 'claude-5-mini',
    name: 'Claude 5 Mini',
    provider: 'Anthropic',
    type: 'proprietary',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1280, mmlu: 86.8, humaneval: 90.5, math: 74.2, gpqa: 62.5, speed_tps: 145, price_input: 1.00, price_output: 5.00 },
    context_window: 200000,
    parameters: 'Non divulgué',
    release_date: '2026-04-10',
    changelog_url: 'https://anthropic.com/news/claude-5-mini',
    is_new: true,
    rank_delta_7d: 2,
    description: 'Version compacte de Claude 5. 90% HumanEval à prix accessible. Meilleur rapport qualité/prix pour le code.',
    best_for: ['Code', 'Rapide', 'Économique', 'Développement'],
    api_available: true,
  },
  {
    id: 'deepseek-r2',
    name: 'DeepSeek-R2',
    provider: 'DeepSeek',
    type: 'open',
    subcategory: 'reasoning',
    subcategory_label: 'Raisonnement',
    scores: { arena_elo: 1350, mmlu: 91.8, humaneval: 94.5, math: 97.8, gpqa: 78.2, speed_tps: 30, price_input: 0.15, price_output: 2.50 },
    context_window: 256000,
    parameters: '1T (MoE)',
    release_date: '2026-02-20',
    changelog_url: 'https://deepseek.ai/blog/deepseek-r2',
    is_new: false,
    rank_delta_7d: 1,
    description: 'Raisonnement open-source record. 97.8% MATH, rivalisant avec o5 à 300x moins cher. Prix imbattable.',
    best_for: ['Raisonnement', 'Mathématiques', 'Science', 'Open-source'],
    api_available: true,
  },
  {
    id: 'llama-5-scout',
    name: 'Llama 5 Scout',
    provider: 'Meta',
    type: 'open',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1265, mmlu: 85.0, humaneval: 86.2, math: 71.5, gpqa: 62.8, speed_tps: 92, price_input: null, price_output: null },
    context_window: 256000,
    parameters: '32B actifs / 256B total (MoE)',
    release_date: '2026-03-28',
    changelog_url: 'https://ai.meta.com/blog/llama-5/',
    is_new: true,
    rank_delta_7d: 3,
    description: 'Version compacte de Llama 5. MoE 256B/32B, rapide et efficient. Idéal pour le déploiement local.',
    best_for: ['Auto-hébergement', 'Efficient', 'Open-source', 'Mobile'],
    api_available: false,
  },
  {
    id: 'kimi-k2-6',
    name: 'Kimi k2.6',
    provider: 'Moonshot AI',
    type: 'proprietary',
    subcategory: 'reasoning',
    subcategory_label: 'Raisonnement',
    scores: { arena_elo: 1312, mmlu: 89.8, humaneval: 91.2, math: 93.5, gpqa: 75.8, speed_tps: 42, price_input: 2.50, price_output: 10.00 },
    context_window: 256000,
    parameters: 'Non divulgué',
    release_date: '2026-02-15',
    changelog_url: 'https://www.moonshot.cn/news/kimi-k2-6',
    is_new: true,
    rank_delta_7d: 4,
    description: 'Dernier modèle de raisonnement de Moonshot AI. Contexte 256K, bat o5 sur MATH et GPQA. Le champion chinois du raisonnement STEM.',
    best_for: ['Raisonnement', 'Mathématiques', 'Science', 'Long-contexte'],
    api_available: true,
  },
  {
    id: 'glm-5',
    name: 'GLM-5',
    provider: 'Zhipu AI',
    type: 'proprietary',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1285, mmlu: 87.5, humaneval: 88.8, math: 78.1, gpqa: 66.2, speed_tps: 78, price_input: 0.50, price_output: 2.00 },
    context_window: 128000,
    parameters: 'Non divulgué',
    release_date: '2026-01-20',
    changelog_url: 'https://open.bigmodel.cn/blog/glm5',
    is_new: false,
    rank_delta_7d: 1,
    description: 'Nouvelle génération de Zhipu AI. Excellent en chinois, multilingue, raisonnement avancé et très compétitif en code à prix cassé.',
    best_for: ['Chinois', 'Multilingue', 'Code', 'Économique'],
    api_available: true,
  },
  {
    id: 'step-3',
    name: 'Step-3',
    provider: 'StepFun',
    type: 'proprietary',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1278, mmlu: 86.9, humaneval: 87.5, math: 79.8, gpqa: 65.5, speed_tps: 62, price_input: 1.20, price_output: 4.50 },
    context_window: 256000,
    parameters: 'Non divulgué',
    release_date: '2026-02-28',
    changelog_url: 'https://www.stepfun.com/news/step-3',
    is_new: true,
    rank_delta_7d: 3,
    description: 'Dernière génération StepFun. Montée spectaculaire dans le classement Arena. Raisonnement avancé et conversation générale très naturelle.',
    best_for: ['Conversation', 'Raisonnement', 'Chinois', 'Code'],
    api_available: true,
  },
  {
    id: 'baichuan-5',
    name: 'Baichuan 5',
    provider: 'Baichuan AI',
    type: 'open',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1268, mmlu: 85.5, humaneval: 86.0, math: 74.2, gpqa: 63.8, speed_tps: 55, price_input: 0.20, price_output: 0.60 },
    context_window: 128000,
    parameters: 'Non divulgué',
    release_date: '2026-01-15',
    changelog_url: 'https://www.baichuan-ai.com/blog/baichuan-5',
    is_new: false,
    rank_delta_7d: 0,
    description: 'Nouvelle génération open-source de Baichuan. Très bon en chinois, programmation et raisonnement. Prix ultra-compétitif.',
    best_for: ['Chinois', 'Code', 'Open-source', 'Économique'],
    api_available: true,
  },
  {
    id: 'command-r2-plus',
    name: 'Command R2+',
    provider: 'Cohere',
    type: 'proprietary',
    subcategory: 'agent',
    subcategory_label: 'Agent',
    scores: { arena_elo: 1252, mmlu: 84.8, humaneval: 85.2, math: 72.5, gpqa: 61.5, speed_tps: 95, price_input: 2.00, price_output: 7.00 },
    context_window: 128000,
    parameters: 'Non divulgué',
    release_date: '2025-12-10',
    changelog_url: 'https://cohere.com/blog/command-r2-plus',
    is_new: false,
    rank_delta_7d: -1,
    description: 'Nouvelle génération entreprise Cohere. Outils natifs (RAG, web, calculatrice). Leader pour les agents autonomes et l\'analyse documentaire.',
    best_for: ['Entreprise', 'RAG', 'Agents', 'Recherche'],
    api_available: true,
  },
  {
    id: 'nous-hermes-4',
    name: 'Nous Hermes 4',
    provider: 'Nous Research',
    type: 'open',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1245, mmlu: 84.2, humaneval: 88.5, math: 70.8, gpqa: 60.2, speed_tps: 65, price_input: null, price_output: null },
    context_window: 128000,
    parameters: '70B',
    release_date: '2026-01-05',
    changelog_url: 'https://nousresearch.com/blog/hermes-4',
    is_new: true,
    rank_delta_7d: 2,
    description: 'Fine-tune open-source communautaire sur base Llama 5. Instruction-following record et créativité exceptionnelle. Culte chez les développeurs indie.',
    best_for: ['Créativité', 'Open-source', 'Fine-tuning', 'Développement'],
    api_available: false,
  },
  {
    id: 'jamba-3',
    name: 'Jamba 3',
    provider: 'AI21 Labs',
    type: 'proprietary',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1238, mmlu: 83.5, humaneval: 84.1, math: 69.5, gpqa: 59.8, speed_tps: 110, price_input: 1.80, price_output: 6.50 },
    context_window: 256000,
    parameters: 'Non divulgué',
    release_date: '2025-11-20',
    changelog_url: 'https://www.ai21.com/blog/jamba-3',
    is_new: false,
    rank_delta_7d: 0,
    description: 'Nouvelle génération hybride Mamba+Transformer. Contexte 512K natif, vitesse record et très efficient sur les longs documents.',
    best_for: ['Contexte long', 'Rapide', 'Entreprise', 'RAG'],
    api_available: true,
  },
  {
    id: 'apple-intelligence-3',
    name: 'Apple Intelligence 3',
    provider: 'Apple',
    type: 'open',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1225, mmlu: 81.8, humaneval: 82.5, math: 68.2, gpqa: 57.5, speed_tps: 280, price_input: null, price_output: null },
    context_window: 32000,
    parameters: '7B',
    release_date: '2026-02-15',
    changelog_url: 'https://machinelearning.apple.com/research/apple-intelligence-3',
    is_new: true,
    rank_delta_7d: 5,
    description: 'Nouveau modèle on-device Apple pour iOS 19/macOS 16. 8B paramètres mais performances proches de modèles 40B grâce aux neural engines Apple Silicon.',
    best_for: ['On-device', 'Mobile', 'Privacy', 'Open-source'],
    api_available: false,
  },
  {
    id: 'gpt-5-mini',
    name: 'GPT-5 Mini',
    provider: 'OpenAI',
    type: 'proprietary',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1295, mmlu: 87.2, humaneval: 88.5, math: 76.8, gpqa: 66.5, speed_tps: 220, price_input: 0.25, price_output: 1.00 },
    context_window: 256000,
    parameters: 'Non divulgué',
    release_date: '2026-04-15',
    changelog_url: 'https://openai.com/news/gpt-5-mini',
    is_new: true,
    rank_delta_7d: 2,
    description: 'Version économique de GPT-5. Performances supérieures à GPT-4.5 à 10x moins cher. Parfait pour la production.',
    best_for: ['Économique', 'Rapide', 'Chatbots', 'Classification'],
    api_available: true,
  },
]
