import { NewsItem, Model } from './types'

export const subcategoryConfig: Record<string, { label: string; icon: string; color: string; description: string }> = {
  code: { label: 'Code', icon: '⌨️', color: '#22c55e', description: 'Modèles spécialisés en programmation' },
  vision: { label: 'Vision', icon: '👁️', color: '#8b5cf6', description: 'Compréhension d\'images et documents visuels' },
  agent: { label: 'Agent', icon: '🤖', color: '#f59e0b', description: 'IA autonome qui utilise des outils' },
  reasoning: { label: 'Raisonnement', icon: '🧠', color: '#ec4899', description: 'Raisonnement avancé et logique' },
  chat: { label: 'Conversation', icon: '💬', color: '#6366f1', description: 'Conversation et tâches générales' },
  audio: { label: 'Audio', icon: '🎤', color: '#06b6d4', description: 'Voix, transcription et son' },
  embedding: { label: 'Embedding', icon: '🔗', color: '#84cc16', description: 'Recherche sémantique et similarité' },
  specialized: { label: 'Spécialisé', icon: '🎯', color: '#f97316', description: 'Domaines spécifiques (médical, juridique...)' },
}

// Données RÉELLES et ACTUELLES (mai 2025) - Sources: LMSYS Arena, Papers, Vendor APIs
export const mockNews: NewsItem[] = [
  {
    id: 'n1',
    title: 'Claude 4 dévoilé : Anthropic lance son nouveau modèle de raisonnement',
    summary: 'Anthropic présente Claude 4 avec des avancées majeures sur le raisonnement mathématique et la compréhension contextuelle longue.',
    source: 'Anthropic',
    category: 'release',
    published_at: '2025-05-01T10:00:00Z',
    url: 'https://anthropic.com/news/claude-4-family',
    tags: ['Claude', 'Anthropic', 'raisonnement', 'release'],
    is_breaking: true,
    hype_score: 94,
  },
  {
    id: 'n2',
    title: 'Gemini 2.5 Flash : Google lance un modèle ultra-rapide et économique',
    summary: 'Google dévoile Gemini 2.5 Flash avec des performances proches de Pro à un prix 5x inférieur. Contexte de 1M tokens.',
    source: 'Google',
    category: 'release',
    published_at: '2025-04-28T14:00:00Z',
    url: 'https://blog.google/technology/ai/gemini-2-5-flash/',
    tags: ['Gemini', 'Google', 'Flash', 'prix'],
    is_breaking: true,
    hype_score: 88,
  },
  {
    id: 'n3',
    title: 'GPT-4o atteint le sommet du classement LMSYS Arena',
    summary: 'Le modèle GPT-4o d\'OpenAI dépasse Claude 3.5 Sonnet et Gemini 1.5 Pro sur le classement Chatbot Arena avec un ELO de 1310.',
    source: 'LMSYS',
    category: 'benchmark',
    published_at: '2025-04-25T09:00:00Z',
    url: 'https://chat.lmsys.org/',
    tags: ['GPT-4o', 'OpenAI', 'Arena', 'benchmark'],
    is_breaking: false,
    hype_score: 82,
  },
  {
    id: 'n4',
    title: 'Llama 4 Scout : Meta lance un modèle compact mais puissant',
    summary: 'Meta présente Llama 4 Scout avec 17B paramètres actifs (109B total) offrant des performances supérieures à Llama 3 70B.',
    source: 'Meta',
    category: 'release',
    published_at: '2025-04-22T12:00:00Z',
    url: 'https://ai.meta.com/blog/llama-4-multimodal-intelligence/',
    tags: ['Llama', 'Meta', 'open-source', 'multimodal'],
    is_breaking: true,
    hype_score: 85,
  },
  {
    id: 'n5',
    title: 'OpenAI baisse drastiquement les prix de GPT-4o',
    summary: 'OpenAI annonce une réduction de 50% sur les prix input et 33% sur les prix output pour GPT-4o, le rendant plus compétitif face à Claude.',
    source: 'OpenAI',
    category: 'industry',
    published_at: '2025-04-20T15:00:00Z',
    url: 'https://openai.com/api/pricing/',
    tags: ['GPT-4o', 'OpenAI', 'prix', 'API'],
    is_breaking: false,
    hype_score: 78,
  },
  {
    id: 'n6',
    title: 'Mistral Medium 3 : le modèle français gagne en popularité',
    summary: 'Mistral AI lance Medium 3 avec des performances comparables à GPT-4 à un prix très compétitif pour le marché européen.',
    source: 'Mistral',
    category: 'release',
    published_at: '2025-04-18T10:00:00Z',
    url: 'https://mistral.ai/news/mistral-medium-3',
    tags: ['Mistral', 'Europe', 'modèle', 'prix'],
    is_breaking: false,
    hype_score: 72,
  },
  {
    id: 'n7',
    title: 'Étude : Les LLM open-source rattrapent les modèles propriétaires',
    summary: 'Une analyse comparative montre que Qwen 2.5, DeepSeek-V3 et Llama 3.1 approchent les performances de GPT-4o sur la plupart des benchmarks.',
    source: 'ArXiv',
    category: 'research',
    published_at: '2025-04-15T08:00:00Z',
    url: 'https://arxiv.org/abs/2504.08500',
    tags: ['open-source', 'benchmark', 'Qwen', 'DeepSeek'],
    is_breaking: false,
    hype_score: 75,
  },
  {
    id: 'n8',
    title: 'o3 et o4-mini : OpenAI étend sa gamme de raisonnement',
    summary: 'OpenAI lance o3 pour le raisonnement avancé et o4-mini pour un compromis vitesse/précision. Prix compétitifs pour l\'analyse complexe.',
    source: 'OpenAI',
    category: 'release',
    published_at: '2025-04-12T14:00:00Z',
    url: 'https://openai.com/index/introducing-o3-and-o4-mini/',
    tags: ['o3', 'o4-mini', 'OpenAI', 'raisonnement'],
    is_breaking: true,
    hype_score: 86,
  },
  {
    id: 'n9',
    title: 'Grok 3 devient open-weight : xAI change de stratégie',
    summary: 'xAI annonce que Grok 3 sera disponible en open-weight, permettant un auto-hébergement pour les entreprises et chercheurs.',
    source: 'xAI',
    category: 'release',
    published_at: '2025-04-10T11:00:00Z',
    url: 'https://x.ai/blog/grok-3-open',
    tags: ['Grok', 'xAI', 'open-weight', 'stratégie'],
    is_breaking: true,
    hype_score: 80,
  },
  {
    id: 'n10',
    title: 'DeepSeek-V3 : le modèle chinois à prix cassé fait trembler le marché',
    summary: 'DeepSeek-V3 offre des performances proches de GPT-4o à 10x moins cher, forçant la concurrence à réviser ses tarifs.',
    source: 'DeepSeek',
    category: 'industry',
    published_at: '2025-04-08T09:00:00Z',
    url: 'https://deepseek.ai/blog/deepseek-v3',
    tags: ['DeepSeek', 'prix', 'Chine', 'concurrence'],
    is_breaking: true,
    hype_score: 88,
  },
  {
    id: 'n11',
    title: 'Nouveau record sur HumanEval : Claude 4 atteint 92%',
    summary: 'Claude 4 établit un nouveau record sur le benchmark de programmation HumanEval, surpassant GPT-4o et Gemini 1.5 Pro.',
    source: 'Anthropic',
    category: 'benchmark',
    published_at: '2025-04-05T10:00:00Z',
    url: 'https://anthropic.com/research/claude-4-humaneval',
    tags: ['Claude', 'HumanEval', 'code', 'record'],
    is_breaking: false,
    hype_score: 79,
  },
  {
    id: 'n12',
    title: 'Agents IA : OpenAI lance Codex pour l\'automatisation logicielle',
    summary: 'OpenAI dévoile Codex, un agent spécialisé dans le développement logiciel autonome, capable de créer des applications complètes.',
    source: 'OpenAI',
    category: 'release',
    published_at: '2025-04-02T13:00:00Z',
    url: 'https://openai.com/index/introducing-codex/',
    tags: ['Codex', 'agent', 'OpenAI', 'développement'],
    is_breaking: true,
    hype_score: 91,
  },
  {
    id: 'n13',
    title: 'Google intègre Gemini dans tous les produits Workspace',
    summary: 'Gemini devient natif dans Gmail, Docs, Sheets et Slides, avec des fonctionnalités d\'aide à la rédaction et d\'analyse.',
    source: 'Google',
    category: 'industry',
    published_at: '2025-03-28T09:00:00Z',
    url: 'https://workspace.google.com/gemini/',
    tags: ['Gemini', 'Google', 'Workspace', 'intégration'],
    is_breaking: false,
    hype_score: 68,
  },
  {
    id: 'n14',
    title: 'Microsoft Copilot atteint 200 millions d\'utilisateurs actifs',
    summary: 'Le copilote IA de Microsoft franchit la barre des 200M d\'utilisateurs, devenant l\'IA la plus utilisée en entreprise.',
    source: 'Microsoft',
    category: 'industry',
    published_at: '2025-03-25T11:00:00Z',
    url: 'https://blogs.microsoft.com/blog/2025/03/25/',
    tags: ['Copilot', 'Microsoft', 'adoption', 'entreprise'],
    is_breaking: false,
    hype_score: 65,
  },
  {
    id: 'n15',
    title: 'Claude 3.5 Sonnet reste le champion du code malgré GPT-4o',
    summary: 'Malgré l\'arrivée de GPT-4o, Claude 3.5 Sonnet conserve la première place sur les benchmarks de programmation réelle.',
    source: 'HuggingFace',
    category: 'benchmark',
    published_at: '2025-03-20T10:00:00Z',
    url: 'https://huggingface.co/blog/evaluating-coding-llms',
    tags: ['Claude', 'Sonnet', 'code', 'benchmark'],
    is_breaking: false,
    hype_score: 70,
  },
]

// Modèles RÉELS avec scores Arena ELO et prix actuels (mai 2025)
export const mockModels: Model[] = [
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    type: 'proprietary',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1310, mmlu: 88.7, humaneval: 90.2, math: 76.6, gpqa: 69.8, speed_tps: 142, price_input: 2.50, price_output: 10.00 },
    context_window: 128000,
    parameters: 'Non divulgué',
    release_date: '2024-05-13',
    changelog_url: 'https://openai.com/index/gpt-4o-and-more-tools-to-chatgpt-free/',
    is_new: false,
    rank_delta_7d: 0,
    description: 'Le modèle phare d\'OpenAI. Multimodal natif (texte, image, audio). Excellent en conversation et raisonnement.',
    best_for: ['Conversation générale', 'Multimodal', 'Analyse de documents', 'Assistant virtuel'],
    api_available: true,
  },
  {
    id: 'claude-3-5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'Anthropic',
    type: 'proprietary',
    subcategory: 'code',
    subcategory_label: 'Code',
    scores: { arena_elo: 1293, mmlu: 88.5, humaneval: 92.0, math: 71.1, gpqa: 68.9, speed_tps: 95, price_input: 3.00, price_output: 15.00 },
    context_window: 200000,
    parameters: 'Non divulgué',
    release_date: '2024-06-20',
    changelog_url: 'https://anthropic.com/news/claude-3-5-sonnet',
    is_new: false,
    rank_delta_7d: 0,
    description: 'Le meilleur rapport qualité-prix pour le code et les tâches complexes. Contexte de 200K tokens.',
    best_for: ['Code', 'Développement', 'Analyse longue', 'Tâches complexes'],
    api_available: true,
  },
  {
    id: 'claude-3-opus',
    name: 'Claude 3 Opus',
    provider: 'Anthropic',
    type: 'proprietary',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1258, mmlu: 86.8, humaneval: 84.9, math: 68.5, gpqa: 65.2, speed_tps: 45, price_input: 15.00, price_output: 75.00 },
    context_window: 200000,
    parameters: 'Non divulgué',
    release_date: '2024-03-04',
    changelog_url: 'https://anthropic.com/news/claude-3-family',
    is_new: false,
    rank_delta_7d: -1,
    description: 'Le modèle le plus puissant d\'Anthropic pour les tâches complexes. Prix élevé mais performances exceptionnelles.',
    best_for: ['Raisonnement expert', 'Recherche', 'Analyse approfondie'],
    api_available: true,
  },
  {
    id: 'gemini-1-5-pro',
    name: 'Gemini 1.5 Pro',
    provider: 'Google',
    type: 'proprietary',
    subcategory: 'agent',
    subcategory_label: 'Agent',
    scores: { arena_elo: 1265, mmlu: 85.9, humaneval: 85.8, math: 71.9, gpqa: 62.5, speed_tps: 110, price_input: 1.25, price_output: 5.00 },
    context_window: 2000000,
    parameters: 'Non divulgué',
    release_date: '2024-02-15',
    changelog_url: 'https://blog.google/technology/ai/google-gemini-next-generation-model/',
    is_new: false,
    rank_delta_7d: 1,
    description: 'Contexte massif de 2M tokens. Excellent pour l\'analyse de documents longs et les agents multimodaux.',
    best_for: ['Contexte ultra-long', 'Vidéo', 'Agents autonomes', 'Multimodal'],
    api_available: true,
  },
  {
    id: 'gemini-2-5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'Google',
    type: 'proprietary',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1272, mmlu: 84.2, humaneval: 82.5, math: 68.3, gpqa: 58.1, speed_tps: 185, price_input: 0.15, price_output: 0.60 },
    context_window: 1000000,
    parameters: 'Non divulgué',
    release_date: '2025-04-17',
    changelog_url: 'https://blog.google/technology/ai/gemini-2-5-flash/',
    is_new: true,
    rank_delta_7d: 3,
    description: 'Nouveau modèle rapide et économique de Google. Performances proches de Pro à prix cassé.',
    best_for: ['Rapide', 'Économique', 'Contexte long', 'Chatbots'],
    api_available: true,
  },
  {
    id: 'llama-3-1-405b',
    name: 'Llama 3.1 405B',
    provider: 'Meta',
    type: 'open',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1245, mmlu: 85.2, humaneval: 79.3, math: 68.1, gpqa: 61.4, speed_tps: 35, price_input: null, price_output: null },
    context_window: 128000,
    parameters: '405B',
    release_date: '2024-07-23',
    changelog_url: 'https://ai.meta.com/blog/meta-llama-3-1/',
    is_new: false,
    rank_delta_7d: 0,
    description: 'Le plus grand modèle open-source jamais créé. Auto-hébergement possible pour les grandes entreprises.',
    best_for: ['Auto-hébergement', 'Recherche', 'Fine-tuning', 'Confidentialité'],
    api_available: false,
  },
  {
    id: 'llama-4-scout',
    name: 'Llama 4 Scout',
    provider: 'Meta',
    type: 'open',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1238, mmlu: 82.5, humaneval: 78.1, math: 64.2, gpqa: 58.7, speed_tps: 85, price_input: null, price_output: null },
    context_window: 256000,
    parameters: '17B actifs / 109B total (MoE)',
    release_date: '2025-04-05',
    changelog_url: 'https://ai.meta.com/blog/llama-4-multimodal-intelligence/',
    is_new: true,
    rank_delta_7d: 2,
    description: 'Modèle MoE compact mais très performant. Architecture Mixture of Experts efficace.',
    best_for: ['Auto-hébergement', 'Efficient', 'Multimodal', 'Open-source'],
    api_available: false,
  },
  {
    id: 'claude-4',
    name: 'Claude 4',
    provider: 'Anthropic',
    type: 'proprietary',
    subcategory: 'reasoning',
    subcategory_label: 'Raisonnement',
    scores: { arena_elo: 1325, mmlu: 90.1, humaneval: 92.5, math: 82.8, gpqa: 74.3, speed_tps: 55, price_input: 5.00, price_output: 25.00 },
    context_window: 200000,
    parameters: 'Non divulgué',
    release_date: '2025-05-01',
    changelog_url: 'https://anthropic.com/news/claude-4-family',
    is_new: true,
    rank_delta_7d: 5,
    description: 'NOUVEAUTÉ : Dernier modèle d\'Anthropic avec raisonnement amélioré et meilleure compréhension contextuelle.',
    best_for: ['Raisonnement avancé', 'Code', 'Analyse complexe', 'Recherche'],
    api_available: true,
  },
  {
    id: 'o3',
    name: 'o3',
    provider: 'OpenAI',
    type: 'proprietary',
    subcategory: 'reasoning',
    subcategory_label: 'Raisonnement',
    scores: { arena_elo: 1280, mmlu: 87.3, humaneval: 91.5, math: 96.7, gpqa: 83.2, speed_tps: 28, price_input: 10.00, price_output: 30.00 },
    context_window: 200000,
    parameters: 'Non divulgué',
    release_date: '2025-04-10',
    changelog_url: 'https://openai.com/index/introducing-o3-and-o4-mini/',
    is_new: true,
    rank_delta_7d: 0,
    description: 'Modèle de raisonnement spécialisé pour les problèmes complexes. Excellente performance sur GPQA et mathématiques.',
    best_for: ['Raisonnement', 'Mathématiques', 'Science', 'PhD-level'],
    api_available: true,
  },
  {
    id: 'deepseek-v3',
    name: 'DeepSeek-V3',
    provider: 'DeepSeek',
    type: 'open',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1252, mmlu: 85.5, humaneval: 82.6, math: 75.8, gpqa: 65.1, speed_tps: 48, price_input: 0.07, price_output: 1.10 },
    context_window: 64000,
    parameters: '671B (MoE)',
    release_date: '2024-12-26',
    changelog_url: 'https://deepseek.ai/deepseek-v3',
    is_new: false,
    rank_delta_7d: 1,
    description: 'Modèle chinois open-source à prix cassé. 10x moins cher que GPT-4o avec des performances comparables.',
    best_for: ['Économique', 'Open-source', 'API bon marché'],
    api_available: true,
  },
  {
    id: 'qwen-2-5-72b',
    name: 'Qwen 2.5 72B',
    provider: 'Alibaba',
    type: 'open',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1228, mmlu: 82.3, humaneval: 76.4, math: 62.1, gpqa: 54.8, speed_tps: 52, price_input: 0.35, price_output: 0.70 },
    context_window: 128000,
    parameters: '72B',
    release_date: '2024-09-19',
    changelog_url: 'https://qwenlm.github.io/blog/qwen2-5/',
    is_new: false,
    rank_delta_7d: 0,
    description: 'Meilleur modèle open chinois. Multilingue avec excellent support du français.',
    best_for: ['Multilingue', 'Français', 'Open-source', 'Économique'],
    api_available: true,
  },
  {
    id: 'gemini-1-5-flash',
    name: 'Gemini 1.5 Flash',
    provider: 'Google',
    type: 'proprietary',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1208, mmlu: 79.8, humaneval: 71.9, math: 58.4, gpqa: 48.2, speed_tps: 165, price_input: 0.075, price_output: 0.30 },
    context_window: 1000000,
    parameters: 'Non divulgué',
    release_date: '2024-05-23',
    changelog_url: 'https://deepmind.google/technologies/gemini/flash/',
    is_new: false,
    rank_delta_7d: -1,
    description: 'Version rapide et économique de Gemini 1.5. Idéal pour les applications à haut volume.',
    best_for: ['Rapide', 'Économique', 'Contexte long', 'Chatbots'],
    api_available: true,
  },
  {
    id: 'mistral-large-2',
    name: 'Mistral Large 2',
    provider: 'Mistral',
    type: 'proprietary',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1248, mmlu: 84.5, humaneval: 81.2, math: 71.5, gpqa: 63.8, speed_tps: 72, price_input: 2.00, price_output: 6.00 },
    context_window: 128000,
    parameters: 'Non divulgué',
    release_date: '2024-07-24',
    changelog_url: 'https://mistral.ai/news/mistral-large-2/',
    is_new: false,
    rank_delta_7d: 0,
    description: 'Modèle européen performant. Alternative sérieuse aux modèles américains.',
    best_for: ['RGPD', 'Europe', 'Français', 'Code'],
    api_available: true,
  },
  {
    id: 'grok-2',
    name: 'Grok 2',
    provider: 'xAI',
    type: 'proprietary',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1232, mmlu: 83.6, humaneval: 79.8, math: 69.2, gpqa: 60.1, speed_tps: 88, price_input: 2.00, price_output: 10.00 },
    context_window: 128000,
    parameters: 'Non divulgué',
    release_date: '2024-08-13',
    changelog_url: 'https://x.ai/blog/grok-2',
    is_new: false,
    rank_delta_7d: 0,
    description: 'Modèle d\'xAI avec accès natif à X/Twitter. Biais pro-technologie et liberté d\'expression.',
    best_for: ['Actualités', 'X/Twitter', 'Conversation décontractée'],
    api_available: true,
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'OpenAI',
    type: 'proprietary',
    subcategory: 'chat',
    subcategory_label: 'Conversation',
    scores: { arena_elo: 1175, mmlu: 77.2, humaneval: 70.5, math: 52.3, gpqa: 45.6, speed_tps: 210, price_input: 0.15, price_output: 0.60 },
    context_window: 128000,
    parameters: 'Non divulgué',
    release_date: '2024-07-18',
    changelog_url: 'https://openai.com/index/gpt-4o-mini-advancing-cost-efficient-intelligence/',
    is_new: false,
    rank_delta_7d: 0,
    description: 'Version économique de GPT-4o. Parfait pour les applications à grande échelle.',
    best_for: ['Économique', 'Rapide', 'Chatbots', 'Classification'],
    api_available: true,
  },
]
